# Generated by Django 4.2.10 on 2024-02-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
